jca_classification:
    resource: "@JcaClassificationBundle/Controller/"
    type:     annotation
    prefix:   /

jca_user:
    resource: "@JcaUserBundle/Controller/"
    type:     annotation
    prefix:   /

jca_blog:
    resource: "@JcaBlogBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
login:
    pattern:   /login
    defaults:  { _controller: IbwJobeetBundle:Default:login }
    
login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    
